openapi: 3.0.1
info:
  title: Record Store
  description: Record Store API.
  version: 1.0.0
servers:
  - url: /v2
paths:
  /artist/all:
    get:
      summary: get all artists
      operationId: getAllArtists
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            format: int32
          required: false
          description: page number
        - in: query
          name: size
          schema:
            type: integer
            format: int32
          required: false
          description: page size
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArtistResponseOpenApi'

components:
  schemas:
    StyleResponseOpenApi:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    NationalityResponseOpenApi:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    ArtistResponseOpenApi:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        nationality:
          $ref: '#/components/schemas/NationalityResponseOpenApi'
        style:
          $ref: '#/components/schemas/StyleResponseOpenApi'